<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

namespace Redis;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The response message containing the greetings
 *
 * Generated from protobuf message <code>redis.RedisReply</code>
 */
class RedisReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string result = 1;</code>
     */
    private $result = '';

    public function __construct() {
        \GPBMetadata\Redis::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string result = 1;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>string result = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->result = $var;

        return $this;
    }

}

