<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

namespace Redis;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>redis.RedisRequest</code>
 */
class RedisRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string action = 1;</code>
     */
    private $action = '';
    /**
     * Generated from protobuf field <code>string param = 2;</code>
     */
    private $param = '';

    public function __construct() {
        \GPBMetadata\Redis::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string action = 1;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string param = 2;</code>
     * @return string
     */
    public function getParam()
    {
        return $this->param;
    }

    /**
     * Generated from protobuf field <code>string param = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->param = $var;

        return $this;
    }

}

