<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redis.proto

namespace GPBMetadata;

class Redis
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7010a0b72656469732e70726f746f12057265646973222d0a0c526564" .
            "697352657175657374120e0a06616374696f6e180120012809120d0a0570" .
            "6172616d180220012809221c0a0a52656469735265706c79120e0a067265" .
            "73756c74180120012809323c0a05526564697312330a07436f6d6d616e64" .
            "12132e72656469732e5265646973526571756573741a112e72656469732e" .
            "52656469735265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

